# loop
print("adityajha")
print("adityajha")
print("adityajha")
print("adityajha")
print("adityajha")
print("adityajha")
print("adityajha")
print("adityajha")
print("adityajha")
print("adityajha")
print("adityajha")
print("adityajha")